parameters:
  "service-dir":
    default: "sdk/purview"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-dir: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/Microsoft.Purview.UnifiedCatalog.ApiService/{version-status}/{version}/CatalogApiService.json"
  "@azure-tools/typespec-python":
    package-dir: "azure-Purview-UnifiedCatalog"
    namespace: "azure.Purview.UnifiedCatalog"
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Purview.UnifiedCatalog"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "Purview-UnifiedCatalog-rest"
    package-details:
      name: "@azure-rest/Purview-UnifiedCatalog"
    flavor: azure
  "@azure-tools/typespec-java":
    package-dir: "azure-Purview-UnifiedCatalog"
    namespace: com.azure.Purview.UnifiedCatalog
    flavor: azure
  "@azure-tools/typespec-go":
    module: "github.com/Azure/azure-sdk-for-go/sdk/purview/azpurviewcatalog"
    service-dir: "sdk/purview"
    package-dir: "azpurviewcatalog"
    module-version: "0.0.1"
    generate-fakes: true
    inject-spans: true
    single-client: true
    flavor: azure
