parameters:
  "service-dir":
    default: "sdk/cognitivelanguage"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/Language/{version-status}/{version}/analyzeconversations-authoring.json"
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.AI.Language.Conversations.Authoring"
    clear-output-folder: true
    model-namespace: false
    namespace: "Azure.AI.Language.Conversations.Authoring"
    flavor: azure
    generate-sample-project: false
  "@azure-tools/typespec-ts":
    title: AnalyzeConversationsAuthoring
    package-dir: "ai-language-conversationauthoring-rest"
    generateMetadata: true
    generate-tests: false
    packageDetails:
      name: "@azure-rest/ai-language-conversationauthoring"
      description: "Language Analyze Conversation Authoring Rest Client"
      version: "1.0.0"
    flavor: azure