parameters:
  "service-dir":
    default: "sdk/chaos"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    omit-unreachable-types: true
    emit-common-types-schema: "never"
    emitter-output-dir: "{project-root}/.."
    arm-types-dir: "{project-root}/../../common-types/resource-management"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.Chaos"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
