emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/json-schema"  
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@typespec/json-schema":
    file-type: "json"
    emitAllModels: false
    emitAllRefs: true    
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
