emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azurefleet.json"
    examples-directory: "examples"
  "@azure-tools/typespec-csharp":
    flavor: azure
    # Added to support generic model conversion from compute VM types
    use-model-reader-writer: true
