parameters:
  service-dir:
    default: "sdk/confidentialledger"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-dir: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    "package-version": "1.2.0b2"
    "package-name": "azure-confidentialledger"
    "package-dir": "azure-confidentialledger"
    "namespace": "azure.confidentialledger"
    "flavor": "azure"
    "generate-test": false
    "generate-sample": false
  "@azure-tools/typespec-client-generator-cli":
    "additionalDirectories": [
      "specification/confidentialledger/data-plane/ConfidentialLedger/Certificate"
    ]
  # Uncomment this line and add "@azure-tools/typespec-java" to your package.json to generate Java code
  # "@azure-tools/typespec-java": true
  # Uncomment this line and add "@azure-tools/typespec-csharp" to your package.json to generate C# code
  # "@azure-tools/typespec-csharp": true
  # Uncomment this line and add "@azure-tools/typespec-ts" to your package.json to generate Typescript code
  # "@azure-tools/typespec-ts": true
