parameters:
  "service-dir":
    default: "sdk/compute"
emit:
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-python":
    package-name: "azure-mgmt-compute"
    package-dir: "azure-mgmt-compute"
    flavor: "azure"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-resource-invalid-action-verb": "Keep"
    "@azure-tools/typespec-azure-resource-manager/arm-post-operation-response-codes": "Check"
    "@azure-tools/typespec-azure-core/casing-style": "Check"
    "@azure-tools/typespec-azure-resource-manager/missing-x-ms-identifiers": "Check"
    "@azure-tools/typespec-azure-core/composition-over-inheritance": 33 => "Check"
    # "@azure-tools/typespec-azure-resource-manager/arm-resource-invalid-envelope-property": "Check"
    "@azure-tools/typespec-azure-resource-manager/arm-resource-provisioning-state": "Check"
    "@azure-tools/typespec-azure-resource-manager/no-empty-model": "3 => suppression?"
    "@azure-tools/typespec-azure-resource-manager/arm-resource-operation": "Check"
    # "@azure-tools/typespec-azure-resource-manager/no-response-body": "Check"
