emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: false
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/bms.json"
    examples-dir: "{project-root}/examples"
    arm-resource-flattening: false
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
