emit:
  - "@azure-tools/typespec-autorest"
#  - "@azure-tools/typespec-providerhub-controller"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": "New rule"
parameters:
  "service-directory-name":
    default: "loadtestservice"
  "provider-name":
    default: "Microsoft.LoadTestService"
  "service-name":
    default: "operations"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{provider-name}/{service-name}/{version-status}/{version}/operations.json"
    omit-unreachable-types: true
    use-read-only-status-schema: true