parameters:
  "service-dir":
    default: "sdk/securitycopilot"
  "version-name":
    default: "2023-08-01-preview"
  "python-sdk-folder":
    default: "./tsp-output/securitycopilot-sdk-for-python/"
  "java-sdk-folder":
    default: "../securitycopilot-sdk-for-java/"
  "js-sdk-folder":
    default: "./tsp-output/securitycopilot-sdk-for-js/"
  "csharp-sdk-folder":
    default: "../securitycopilot-sdk-for-net/"
  "package": 
    default: "Microsoft.Security.Copilot.SkillsetAuthoring"
  "autorest-dir":
    default: "../openapi2/preview"
  "openapi-dir":
    default: "../openapi3/preview"
emit: [
  "@typespec/openapi3",
  "@azure-tools/typespec-autorest",
  "@azure-tools/typespec-csharp",
  "@azure-tools/typespec-java",
  "@azure-tools/typespec-python",
  "@azure-tools/typespec-ts"
]
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/{openapi-dir}"
    output-file: "SecurityCopilotSkillContextAPI.OpenAPI3.{version-name}"
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/{autorest-dir}"
    output-file: "SecurityCopilotSkillContextAPI.OpenAPI2.{version-name}"
  "@azure-tools/typespec-csharp":
    package-dir: "Microsoft.Security.Copilot.SkillsetAuthoring"
    namespace: "{package-dir}"
    clear-output-folder: false
    save-inputs: true
    generate-models: true
    models-public: true
  "@azure-tools/typespec-java":
    package-dir: "Microsoft.Security.Copilot.SkillsetAuthoring"
    namespace: "{package-dir}"
    clear-output-folder: false
    save-inputs: true
  "@azure-tools/typespec-python":
    package-dir: "Microsoft.Security.Copilot.SkillsetAuthoring"
    namespace: "{package-dir}"
    clear-output-folder: false
    save-inputs: true
  "@azure-tools/typespec-ts":
    package-dir: "Microsoft.Security.Copilot.SkillsetAuthoring"
    namespace: "{package-dir}"
    clear-output-folder: false
    save-inputs: true