linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: resource-manager
    use-read-only-status-schema: true
