parameters:
  "service-dir":
    default: "sdk/containerorchestratorruntime"
  swagger-repo-dir:
    default: "{project-root}/swagger"

emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: resource-manager
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/kubernetesruntime.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.ContainerOrchestratorRuntime"
    flavor: azure
    clear-output-folder: true
    use-write-core: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-containerorchestratorruntime"
    namespace: "azure.mgmt.containerorchestratorruntime"
    flavor: "azure"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-ts":
    "service-dir": kubernetesruntime
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    experimentalExtensibleEnums: true
    package-dir: "arm-containerorchestratorruntime"
    flavor: "azure"
    packageDetails:
      name: "@azure/arm-containerorchestratorruntime"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-containerorchestratorruntime"
    service-name: "Container Orchestrator Runtime"
    flavor: "azure"
  "@azure-tools/typespec-go":
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    service-dir: "sdk/containerorchestratorruntime"
    package-dir: "armcontainerorchestratorruntime"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
