trigger: none

jobs:
- job:
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - task: GoTool@0
    inputs:
      version: '1.22.2'
  
  - script: |
      echo '##vso[task.prependpath]$(HOME)/go/bin'
    displayName: 'Set Environment Variables'

  - script: |
      go version
      go install github.com/azure/armstrong@109e9a46faa57c2c5af762019342dff3030f7d79
    displayName: 'Install go dependencies'

  - pwsh: |
      $(Build.SourcesDirectory)/eng/scripts/Armstrong-Validation.ps1 -Verbose
    displayName: Armstrong Validation
    ignoreLASTEXITCODE: true
