trigger: none
pr:
  paths:
    include:
      - specification/**

jobs:
  - job: SwaggerApiDocPreview

    pool:
      name: $(LINUXPOOL)
      vmImage: $(LINUXVMIMAGE)
      os: linux

    variables:
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml
      
      - name: BranchName
        value: preview/$(Build.Repository.Name)/pr/$(System.PullRequest.PullRequestNumber)/build/$(Build.BuildId)/attempt/$(System.JobAttempt)
      
      - name: CurrentBuildUrl
        value: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)

    steps:
      - bash: |
          gh api repos/Azure/$(Build.Repository.Name)/statuses/$(Build.SourceVersion) \
            -f state='pending' \
            -f target_url='$(CurrentBuildUrl)' \
            -f description='Starting build' \
            -f context='Swagger ApiDocPreview'
        displayName: 'Set PR status to pending'
        env:
          GH_TOKEN: $(azuresdk-github-pat)

      # TODO: Use sparse checkout instead
      - checkout: self
        # Fetch depth required to get list of changed files
        fetchDepth: 2

      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
        parameters:
          SkipCheckoutNone: true
          TokenToUseForAuth: $(azuresdk-github-pat)
          # Path does not need to be set because sparse-checkout.yml already
          # checks out files in the repo root
          Repositories:
            - Name: MicrosoftDocs/AzureRestPreview
              # TODO: use main
              Commitish: refs/heads/doc-preview-migration-test
              WorkingDirectory: AzureRestPreview

      - template: /eng/pipelines/templates/steps/npm-install.yml

      # TODO: Use variables for triggering repository instead of hardcoding
      - script: |
          npm exec --no -- api-doc-preview --output $(System.DefaultWorkingDirectory)/AzureRestPreview
        displayName: 'Generate Swagger API documentation preview'
        workingDirectory: .github/shared

      - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
        parameters:
          WorkingDirectory: AzureRestPreview
          BaseRepoOwner: MicrosoftDocs
          TargetRepoOwner: MicrosoftDocs
          TargetRepoName: AzureRestPreview
          # TODO: Determine this value at runtime
          BaseRepoBranch: $(BranchName)
          CommitMsg: |
            Update API Doc Preview
            Build: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
            PR: $(System.PullRequest.SourceRepositoryURI)/pull/$(System.PullRequest.PullRequestId)

      - task: AzureCLI@2
        displayName: Start docs build
        inputs:
          azureSubscription: msdocs-apidrop-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            az pipelines build queue
            --organization "https://dev.azure.com/apidrop/"
            --project "Content CI"
            --definition-id "8120"
            --variables 'params={"target_repo":{"url":"https://github.com/MicrosoftDocs/AzureRestPreview","branch":"$(BranchName)"}, "source_of_truth": "code"}'
            | tee buildstart.json

      - task: AzureCLI@2
        displayName: Wait for docs build to finish
        # Retry on failure to handle transient issues or builds that run longer
        # than the token used by az CLI is valid
        retryCountOnTaskFailure: 3
        inputs:
          azureSubscription: msdocs-apidrop-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: eng/scripts/api-doc-preview-wait.mjs

      - script: eng/scripts/api-doc-preview-interpret.mjs
        displayName: Output results
