parameters:
  "service-dir":
    default: "sdk/ai"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - ["@azure-tools/typespec-ts"]
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
  disable:
    "@azure-tools/typespec-azure-core/casing-style": "Disabled since JSON payload in REST API does not conform to Azure guidelines with regards to casing"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    package-mode: dataplane
    package-dir: "azure-ai-inference"
    package-name: "{package-dir}"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "ai-inference"
    packageDetails:
      name: "@azure/ai-inference"
      description: "Inference API for Azure-supported AI models"
      version: "1.0.0-beta.1"
