parameters:
  "service-dir":
    default: "sdk/ai"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/openapi3"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    omit-unreachable-types: true
    emit-lro-options: "none"
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../"
    output-file: "{output-folder-base}/OpenApiV3/{version}/openapi.yaml"
  "@azure-tools/typespec-python":
    package-mode: dataplane
    package-dir: "azure-ai-inference"
    package-name: "{package-dir}"
    package-version: "1.0.0b1"
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.AI.Inference"
    namespace: "Azure.AI.Inference"
    clear-output-folder: true
    model-namespace: false
    flavor: azure
