parameters:
  "service-dir":
    default: "sdk/cognitiveservices"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    # Intentionally not overwriting the data-plane spec files & gitignoring the output of this emitter
    # since this specification is only intended for generating the SDK for now
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/tsp-output"
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/@azure-tools/typespec-autorest/{version-status}/{version}/FastTranscription.json"
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.AI.SpeechToText.FastTranscription"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
    flavor: azure
  "@azure-tools/typespec-java":
    package-dir: "azure-ai-speechtotext-fasttranscription"
    namespace: com.azure.ai.speechtotext.fasttranscription
    partial-update: true
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "ai-speechtotext-fasttranscription"
    packageDetails:
      name: "@azure-rest/ai-speechtotext-fasttranscription"
      version: "1.0.0"
      description: "SpeechToText Fast Transcription Service"
    flavor: azure
  "@azure-tools/typespec-python":
    package-dir: "azure-ai-speechtotext-fasttranscription"
    package-version: "1.0.0"
    package-name: "{package-dir}"
    package-pprint-name: '"Azure AI SpeechToText Fast Transcription"'
    flavor: azure
    generate-test: true
    generate-sample: true
