parameters:
  "service-dir":
    default: "sdk/iotoperations"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/iotoperations.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-iotoperations"
    package-name: "{package-dir}"
    flavor: "azure"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.IoTOperations"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
