name: Setup Node 20 and run `npm ci`
description: Uses specified Node version and runs npm commands to set up the environment for REST API CI

inputs:
  node-version:
    description: 'Node version to use'
    default: 20.x

runs:
  using: "composite"

  steps:
    - name: Use Node ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm ci

    - run: npm ls -a
      continue-on-error: true
