name: Copilot Setup Steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      checks: read
      statuses: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status
          
      - name: Azure Login with Workload Identity Federation
        uses: azure/login@v2
        with:
          client-id: "936c56f0-298b-467f-b702-3ad5bf4b15c1"
          tenant-id: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          allow-no-subscriptions: true
          
      - name: Run MCP server
        run: pwsh eng/common/mcp/azure-sdk-mcp.ps1 -Run -InstallDirectory /home/runner/work/_temp/.azure-sdk-mcp/azsdk
        working-directory: /home/runner/work/azure-rest-api-specs/azure-rest-api-specs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

