name: LintDiff (Preview)

on: pull_request

permissions:
  contents: read

jobs:
  lintdiff:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout eng
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            eng/
            .github/

      - name: Checkout 'after' state
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: after

      - name: Checkout 'before' state
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: before

      - name: Setup Node and install deps
        uses: ./.github/actions/setup-node-install-deps

      # TODO: This can probably be updated to run directly from JS
      # TODO: default workspace is the after/ folder
      - name: Get changed files
        run: |
          ."./eng/scripts/ChangedFiles-Functions.ps1"
          Set-Location ./after
          Get-ChangedFiles | Set-Content -Path ../changed-files.txt
          Get-Location
          Get-Content ../changed-files.txt
        shell: pwsh

      - name: Run LintDiff
        run: |
          npm exec --no -- lint-diff \
            --before before \
            --after after \
            --changed-files-path changed-files.txt \
            --out-file placeholder.txt
