parameters:
  "service-dir":
    default: "sdk/manufacturingdatasolution"
  "service-name":
    default: "Microsoft.Industries.ManufacturingDataSolution.Copilot"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/../"
    omit-unreachable-types: true
    output-file: "./data-plane/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    package-dir: "microsoft-industries-manufacturingdatasolution-copilot"
    package-name: "{package-dir}"
    package-mode: dataplane
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Microsoft.Industries.ManufacturingDataSolution.Copilot"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "microsoft-industries-manufacturingdatasolution-copilot"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/microsoft-industry-manufacturing-mds-copilot"
      description: "Microsoft.Industry.Manufacturing.MDS.Copilot"
    flavor: azure
  "@azure-tools/typespec-java":
    package-dir: "azure-microsoft-industry-manufacturing-mds-copilot"
    namespace: "com.azure.microsoft.industry.manufacturing.mds.copilot"
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/dataplane/microsoft-industries-manufacturingdatasolution-copilot"
    package-dir: "azure-microsoft-industries-manufacturingdatasolution-copilot"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
