parameters:
  "service-dir":
    default: "sdk/manufacturingdatasolution"
  "service-name":
    default: "Microsoft.Industries.ManufacturingDataSolution.Copilot"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/../"
    omit-unreachable-types: true
    output-file: "./data-plane/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    package-dir: "microsoft-industry-manufacturing-mds-copilot"
    package-name: "{package-dir}"
    package-mode: dataplane
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Microsoft.Industry.Manufacturing.MDS.Copilot"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "microsoft-industry-manufacturing-mds-copilot"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/microsoft-industry-manufacturing-mds-copilot"
      description: "Microsoft.Industry.Manufacturing.MDS.Copilot"
    flavor: azure
  "@azure-tools/typespec-java":
    package-dir: "microsoft-industry-manufacturing-mds-copilot"
    namespace: "com.microsoft.industry.manufacturing.mds.copilot"
    flavor: azure
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
